root = "."
tmp_dir = "tmp"

[build]
  pre_cmd = ["templ generate"]
  bin = "./tmp/main"
  # cmd = "make front"
  cmd = "go build -o ./tmp/main ."
  delay = 100 
  exclude_dir = ["assets", "tmp", "vendor", "ts"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "css"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = true 
  proxy_port = 7331 
  app_port = 5000
